# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class AdminMediationDeny(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mediator_terms': 'list[str]',
        'recipient_terms': 'list[str]'
    }

    attribute_map = {
        'mediator_terms': 'mediator_terms',
        'recipient_terms': 'recipient_terms'
    }

    def __init__(self, mediator_terms=None, recipient_terms=None, _configuration=None):  # noqa: E501
        """AdminMediationDeny - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._mediator_terms = None
        self._recipient_terms = None
        self.discriminator = None

        if mediator_terms is not None:
            self.mediator_terms = mediator_terms
        if recipient_terms is not None:
            self.recipient_terms = recipient_terms

    @property
    def mediator_terms(self):
        """Gets the mediator_terms of this AdminMediationDeny.  # noqa: E501

        List of mediator rules for recipient  # noqa: E501

        :return: The mediator_terms of this AdminMediationDeny.  # noqa: E501
        :rtype: list[str]
        """
        return self._mediator_terms

    @mediator_terms.setter
    def mediator_terms(self, mediator_terms):
        """Sets the mediator_terms of this AdminMediationDeny.

        List of mediator rules for recipient  # noqa: E501

        :param mediator_terms: The mediator_terms of this AdminMediationDeny.  # noqa: E501
        :type: list[str]
        """

        self._mediator_terms = mediator_terms

    @property
    def recipient_terms(self):
        """Gets the recipient_terms of this AdminMediationDeny.  # noqa: E501

        List of recipient rules for mediation  # noqa: E501

        :return: The recipient_terms of this AdminMediationDeny.  # noqa: E501
        :rtype: list[str]
        """
        return self._recipient_terms

    @recipient_terms.setter
    def recipient_terms(self, recipient_terms):
        """Sets the recipient_terms of this AdminMediationDeny.

        List of recipient rules for mediation  # noqa: E501

        :param recipient_terms: The recipient_terms of this AdminMediationDeny.  # noqa: E501
        :type: list[str]
        """

        self._recipient_terms = recipient_terms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdminMediationDeny, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdminMediationDeny):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdminMediationDeny):
            return True

        return self.to_dict() != other.to_dict()
