# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class CreateInvitationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mediation_id': 'str',
        'metadata': 'object',
        'recipient_keys': 'list[str]',
        'routing_keys': 'list[str]',
        'service_endpoint': 'str'
    }

    attribute_map = {
        'mediation_id': 'mediation_id',
        'metadata': 'metadata',
        'recipient_keys': 'recipient_keys',
        'routing_keys': 'routing_keys',
        'service_endpoint': 'service_endpoint'
    }

    def __init__(self, mediation_id=None, metadata=None, recipient_keys=None, routing_keys=None, service_endpoint=None, _configuration=None):  # noqa: E501
        """CreateInvitationRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._mediation_id = None
        self._metadata = None
        self._recipient_keys = None
        self._routing_keys = None
        self._service_endpoint = None
        self.discriminator = None

        if mediation_id is not None:
            self.mediation_id = mediation_id
        if metadata is not None:
            self.metadata = metadata
        if recipient_keys is not None:
            self.recipient_keys = recipient_keys
        if routing_keys is not None:
            self.routing_keys = routing_keys
        if service_endpoint is not None:
            self.service_endpoint = service_endpoint

    @property
    def mediation_id(self):
        """Gets the mediation_id of this CreateInvitationRequest.  # noqa: E501

        Identifier for active mediation record to be used  # noqa: E501

        :return: The mediation_id of this CreateInvitationRequest.  # noqa: E501
        :rtype: str
        """
        return self._mediation_id

    @mediation_id.setter
    def mediation_id(self, mediation_id):
        """Sets the mediation_id of this CreateInvitationRequest.

        Identifier for active mediation record to be used  # noqa: E501

        :param mediation_id: The mediation_id of this CreateInvitationRequest.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                mediation_id is not None and not re.search(r'[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}', mediation_id)):  # noqa: E501
            raise ValueError(r"Invalid value for `mediation_id`, must be a follow pattern or equal to `/[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}/`")  # noqa: E501

        self._mediation_id = mediation_id

    @property
    def metadata(self):
        """Gets the metadata of this CreateInvitationRequest.  # noqa: E501

        Optional metadata to attach to the connection created with the invitation  # noqa: E501

        :return: The metadata of this CreateInvitationRequest.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this CreateInvitationRequest.

        Optional metadata to attach to the connection created with the invitation  # noqa: E501

        :param metadata: The metadata of this CreateInvitationRequest.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    @property
    def recipient_keys(self):
        """Gets the recipient_keys of this CreateInvitationRequest.  # noqa: E501

        List of recipient keys  # noqa: E501

        :return: The recipient_keys of this CreateInvitationRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._recipient_keys

    @recipient_keys.setter
    def recipient_keys(self, recipient_keys):
        """Sets the recipient_keys of this CreateInvitationRequest.

        List of recipient keys  # noqa: E501

        :param recipient_keys: The recipient_keys of this CreateInvitationRequest.  # noqa: E501
        :type: list[str]
        """

        self._recipient_keys = recipient_keys

    @property
    def routing_keys(self):
        """Gets the routing_keys of this CreateInvitationRequest.  # noqa: E501

        List of routing keys  # noqa: E501

        :return: The routing_keys of this CreateInvitationRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._routing_keys

    @routing_keys.setter
    def routing_keys(self, routing_keys):
        """Sets the routing_keys of this CreateInvitationRequest.

        List of routing keys  # noqa: E501

        :param routing_keys: The routing_keys of this CreateInvitationRequest.  # noqa: E501
        :type: list[str]
        """

        self._routing_keys = routing_keys

    @property
    def service_endpoint(self):
        """Gets the service_endpoint of this CreateInvitationRequest.  # noqa: E501

        Connection endpoint  # noqa: E501

        :return: The service_endpoint of this CreateInvitationRequest.  # noqa: E501
        :rtype: str
        """
        return self._service_endpoint

    @service_endpoint.setter
    def service_endpoint(self, service_endpoint):
        """Sets the service_endpoint of this CreateInvitationRequest.

        Connection endpoint  # noqa: E501

        :param service_endpoint: The service_endpoint of this CreateInvitationRequest.  # noqa: E501
        :type: str
        """

        self._service_endpoint = service_endpoint

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateInvitationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateInvitationRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateInvitationRequest):
            return True

        return self.to_dict() != other.to_dict()
