# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class MediationRecord(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'connection_id': 'str',
        'created_at': 'str',
        'endpoint': 'str',
        'mediation_id': 'str',
        'mediator_terms': 'list[str]',
        'recipient_terms': 'list[str]',
        'role': 'str',
        'routing_keys': 'list[str]',
        'state': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'connection_id': 'connection_id',
        'created_at': 'created_at',
        'endpoint': 'endpoint',
        'mediation_id': 'mediation_id',
        'mediator_terms': 'mediator_terms',
        'recipient_terms': 'recipient_terms',
        'role': 'role',
        'routing_keys': 'routing_keys',
        'state': 'state',
        'updated_at': 'updated_at'
    }

    def __init__(self, connection_id=None, created_at=None, endpoint=None, mediation_id=None, mediator_terms=None, recipient_terms=None, role=None, routing_keys=None, state=None, updated_at=None, _configuration=None):  # noqa: E501
        """MediationRecord - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._connection_id = None
        self._created_at = None
        self._endpoint = None
        self._mediation_id = None
        self._mediator_terms = None
        self._recipient_terms = None
        self._role = None
        self._routing_keys = None
        self._state = None
        self._updated_at = None
        self.discriminator = None

        self.connection_id = connection_id
        if created_at is not None:
            self.created_at = created_at
        if endpoint is not None:
            self.endpoint = endpoint
        if mediation_id is not None:
            self.mediation_id = mediation_id
        if mediator_terms is not None:
            self.mediator_terms = mediator_terms
        if recipient_terms is not None:
            self.recipient_terms = recipient_terms
        self.role = role
        if routing_keys is not None:
            self.routing_keys = routing_keys
        if state is not None:
            self.state = state
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def connection_id(self):
        """Gets the connection_id of this MediationRecord.  # noqa: E501


        :return: The connection_id of this MediationRecord.  # noqa: E501
        :rtype: str
        """
        return self._connection_id

    @connection_id.setter
    def connection_id(self, connection_id):
        """Sets the connection_id of this MediationRecord.


        :param connection_id: The connection_id of this MediationRecord.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and connection_id is None:
            raise ValueError("Invalid value for `connection_id`, must not be `None`")  # noqa: E501

        self._connection_id = connection_id

    @property
    def created_at(self):
        """Gets the created_at of this MediationRecord.  # noqa: E501

        Time of record creation  # noqa: E501

        :return: The created_at of this MediationRecord.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this MediationRecord.

        Time of record creation  # noqa: E501

        :param created_at: The created_at of this MediationRecord.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                created_at is not None and not re.search(r'^\\d{4}-\\d\\d-\\d\\d[T ]\\d\\d:\\d\\d(?:\\:(?:\\d\\d(?:\\.\\d{1,6})?))?(?:[+-]\\d\\d:?\\d\\d|Z|)$', created_at)):  # noqa: E501
            raise ValueError(r"Invalid value for `created_at`, must be a follow pattern or equal to `/^\\d{4}-\\d\\d-\\d\\d[T ]\\d\\d:\\d\\d(?:\\:(?:\\d\\d(?:\\.\\d{1,6})?))?(?:[+-]\\d\\d:?\\d\\d|Z|)$/`")  # noqa: E501

        self._created_at = created_at

    @property
    def endpoint(self):
        """Gets the endpoint of this MediationRecord.  # noqa: E501


        :return: The endpoint of this MediationRecord.  # noqa: E501
        :rtype: str
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint):
        """Sets the endpoint of this MediationRecord.


        :param endpoint: The endpoint of this MediationRecord.  # noqa: E501
        :type: str
        """

        self._endpoint = endpoint

    @property
    def mediation_id(self):
        """Gets the mediation_id of this MediationRecord.  # noqa: E501


        :return: The mediation_id of this MediationRecord.  # noqa: E501
        :rtype: str
        """
        return self._mediation_id

    @mediation_id.setter
    def mediation_id(self, mediation_id):
        """Sets the mediation_id of this MediationRecord.


        :param mediation_id: The mediation_id of this MediationRecord.  # noqa: E501
        :type: str
        """

        self._mediation_id = mediation_id

    @property
    def mediator_terms(self):
        """Gets the mediator_terms of this MediationRecord.  # noqa: E501


        :return: The mediator_terms of this MediationRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._mediator_terms

    @mediator_terms.setter
    def mediator_terms(self, mediator_terms):
        """Sets the mediator_terms of this MediationRecord.


        :param mediator_terms: The mediator_terms of this MediationRecord.  # noqa: E501
        :type: list[str]
        """

        self._mediator_terms = mediator_terms

    @property
    def recipient_terms(self):
        """Gets the recipient_terms of this MediationRecord.  # noqa: E501


        :return: The recipient_terms of this MediationRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._recipient_terms

    @recipient_terms.setter
    def recipient_terms(self, recipient_terms):
        """Sets the recipient_terms of this MediationRecord.


        :param recipient_terms: The recipient_terms of this MediationRecord.  # noqa: E501
        :type: list[str]
        """

        self._recipient_terms = recipient_terms

    @property
    def role(self):
        """Gets the role of this MediationRecord.  # noqa: E501


        :return: The role of this MediationRecord.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this MediationRecord.


        :param role: The role of this MediationRecord.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    @property
    def routing_keys(self):
        """Gets the routing_keys of this MediationRecord.  # noqa: E501


        :return: The routing_keys of this MediationRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._routing_keys

    @routing_keys.setter
    def routing_keys(self, routing_keys):
        """Sets the routing_keys of this MediationRecord.


        :param routing_keys: The routing_keys of this MediationRecord.  # noqa: E501
        :type: list[str]
        """

        self._routing_keys = routing_keys

    @property
    def state(self):
        """Gets the state of this MediationRecord.  # noqa: E501

        Current record state  # noqa: E501

        :return: The state of this MediationRecord.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this MediationRecord.

        Current record state  # noqa: E501

        :param state: The state of this MediationRecord.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def updated_at(self):
        """Gets the updated_at of this MediationRecord.  # noqa: E501

        Time of last record update  # noqa: E501

        :return: The updated_at of this MediationRecord.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this MediationRecord.

        Time of last record update  # noqa: E501

        :param updated_at: The updated_at of this MediationRecord.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                updated_at is not None and not re.search(r'^\\d{4}-\\d\\d-\\d\\d[T ]\\d\\d:\\d\\d(?:\\:(?:\\d\\d(?:\\.\\d{1,6})?))?(?:[+-]\\d\\d:?\\d\\d|Z|)$', updated_at)):  # noqa: E501
            raise ValueError(r"Invalid value for `updated_at`, must be a follow pattern or equal to `/^\\d{4}-\\d\\d-\\d\\d[T ]\\d\\d:\\d\\d(?:\\:(?:\\d\\d(?:\\.\\d{1,6})?))?(?:[+-]\\d\\d:?\\d\\d|Z|)$/`")  # noqa: E501

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MediationRecord, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MediationRecord):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MediationRecord):
            return True

        return self.to_dict() != other.to_dict()
