# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class PresentationPreview(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'attributes': 'list[PresAttrSpec]',
        'predicates': 'list[PresPredSpec]'
    }

    attribute_map = {
        'type': '@type',
        'attributes': 'attributes',
        'predicates': 'predicates'
    }

    def __init__(self, type=None, attributes=None, predicates=None, _configuration=None):  # noqa: E501
        """PresentationPreview - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._type = None
        self._attributes = None
        self._predicates = None
        self.discriminator = None

        if type is not None:
            self.type = type
        self.attributes = attributes
        self.predicates = predicates

    @property
    def type(self):
        """Gets the type of this PresentationPreview.  # noqa: E501

        Message type identifier  # noqa: E501

        :return: The type of this PresentationPreview.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PresentationPreview.

        Message type identifier  # noqa: E501

        :param type: The type of this PresentationPreview.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def attributes(self):
        """Gets the attributes of this PresentationPreview.  # noqa: E501


        :return: The attributes of this PresentationPreview.  # noqa: E501
        :rtype: list[PresAttrSpec]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this PresentationPreview.


        :param attributes: The attributes of this PresentationPreview.  # noqa: E501
        :type: list[PresAttrSpec]
        """
        if self._configuration.client_side_validation and attributes is None:
            raise ValueError("Invalid value for `attributes`, must not be `None`")  # noqa: E501

        self._attributes = attributes

    @property
    def predicates(self):
        """Gets the predicates of this PresentationPreview.  # noqa: E501


        :return: The predicates of this PresentationPreview.  # noqa: E501
        :rtype: list[PresPredSpec]
        """
        return self._predicates

    @predicates.setter
    def predicates(self, predicates):
        """Sets the predicates of this PresentationPreview.


        :param predicates: The predicates of this PresentationPreview.  # noqa: E501
        :type: list[PresPredSpec]
        """
        if self._configuration.client_side_validation and predicates is None:
            raise ValueError("Invalid value for `predicates`, must not be `None`")  # noqa: E501

        self._predicates = predicates

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PresentationPreview, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PresentationPreview):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PresentationPreview):
            return True

        return self.to_dict() != other.to_dict()
