# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class RevRegUpdateTailsFileUri(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tails_public_uri': 'str'
    }

    attribute_map = {
        'tails_public_uri': 'tails_public_uri'
    }

    def __init__(self, tails_public_uri=None, _configuration=None):  # noqa: E501
        """RevRegUpdateTailsFileUri - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._tails_public_uri = None
        self.discriminator = None

        self.tails_public_uri = tails_public_uri

    @property
    def tails_public_uri(self):
        """Gets the tails_public_uri of this RevRegUpdateTailsFileUri.  # noqa: E501

        Public URI to the tails file  # noqa: E501

        :return: The tails_public_uri of this RevRegUpdateTailsFileUri.  # noqa: E501
        :rtype: str
        """
        return self._tails_public_uri

    @tails_public_uri.setter
    def tails_public_uri(self, tails_public_uri):
        """Sets the tails_public_uri of this RevRegUpdateTailsFileUri.

        Public URI to the tails file  # noqa: E501

        :param tails_public_uri: The tails_public_uri of this RevRegUpdateTailsFileUri.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and tails_public_uri is None:
            raise ValueError("Invalid value for `tails_public_uri`, must not be `None`")  # noqa: E501

        self._tails_public_uri = tails_public_uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RevRegUpdateTailsFileUri, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RevRegUpdateTailsFileUri):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RevRegUpdateTailsFileUri):
            return True

        return self.to_dict() != other.to_dict()
