# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class V20CredFilterDIF(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'some_dif_criterion': 'str'
    }

    attribute_map = {
        'some_dif_criterion': 'some_dif_criterion'
    }

    def __init__(self, some_dif_criterion=None, _configuration=None):  # noqa: E501
        """V20CredFilterDIF - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._some_dif_criterion = None
        self.discriminator = None

        if some_dif_criterion is not None:
            self.some_dif_criterion = some_dif_criterion

    @property
    def some_dif_criterion(self):
        """Gets the some_dif_criterion of this V20CredFilterDIF.  # noqa: E501

        Placeholder for W3C/DIF/JSON-LD filtration criterion  # noqa: E501

        :return: The some_dif_criterion of this V20CredFilterDIF.  # noqa: E501
        :rtype: str
        """
        return self._some_dif_criterion

    @some_dif_criterion.setter
    def some_dif_criterion(self, some_dif_criterion):
        """Sets the some_dif_criterion of this V20CredFilterDIF.

        Placeholder for W3C/DIF/JSON-LD filtration criterion  # noqa: E501

        :param some_dif_criterion: The some_dif_criterion of this V20CredFilterDIF.  # noqa: E501
        :type: str
        """

        self._some_dif_criterion = some_dif_criterion

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V20CredFilterDIF, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V20CredFilterDIF):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V20CredFilterDIF):
            return True

        return self.to_dict() != other.to_dict()
