version: "3"
services:
  ngrok-company:
    image: wernight/ngrok
    command: ngrok http agent-company:3000 --log stdout
  agent-company:
    image: acapy-toolbox-ngrok
    build:
      context: ../
      dockerfile: ./demo2/Dockerfile.demo
    environment:
      NGROK_NAME: ngrok-company
    ports:
      - "3001:3001"
    command: aca-py start --arg-file ./configs/company.yml

  ngrok-factory:
    image: wernight/ngrok
    command: ngrok http agent-factory:3002 --log stdout
  agent-factory:
    image: acapy-toolbox-ngrok
    environment:
      NGROK_NAME: ngrok-factory
    ports:
      - "3003:3003"
    command: aca-py start --arg-file ./configs/factory.yml 
