# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.did_exchange_api import DidExchangeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDidExchangeApi(unittest.TestCase):
    """DidExchangeApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.did_exchange_api.DidExchangeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_didexchange_conn_id_accept_invitation_post(self):
        """Test case for didexchange_conn_id_accept_invitation_post

        Accept a stored connection invitation  # noqa: E501
        """
        pass

    def test_didexchange_conn_id_accept_request_post(self):
        """Test case for didexchange_conn_id_accept_request_post

        Accept a stored connection request  # noqa: E501
        """
        pass

    def test_didexchange_create_request_post(self):
        """Test case for didexchange_create_request_post

        Create request against public DID's implicit invitation  # noqa: E501
        """
        pass

    def test_didexchange_receive_request_post(self):
        """Test case for didexchange_receive_request_post

        Receive request against public DID's implicit invitation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
