# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.basicmessage_api import BasicmessageApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBasicmessageApi(unittest.TestCase):
    """BasicmessageApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.basicmessage_api.BasicmessageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_connections_conn_id_send_message_post(self):
        """Test case for connections_conn_id_send_message_post

        Send a basic message to a connection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
