# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.out_of_band_api import OutOfBandApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOutOfBandApi(unittest.TestCase):
    """OutOfBandApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.out_of_band_api.OutOfBandApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_out_of_band_create_invitation_post(self):
        """Test case for out_of_band_create_invitation_post

        Create a new connection invitation  # noqa: E501
        """
        pass

    def test_out_of_band_receive_invitation_post(self):
        """Test case for out_of_band_receive_invitation_post

        Receive a new connection invitation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
