# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.schema_api import SchemaApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSchemaApi(unittest.TestCase):
    """SchemaApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.schema_api.SchemaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_schemas_created_get(self):
        """Test case for schemas_created_get

        Search for matching schema that agent originated  # noqa: E501
        """
        pass

    def test_schemas_post(self):
        """Test case for schemas_post

        Sends a schema to the ledger  # noqa: E501
        """
        pass

    def test_schemas_schema_id_get(self):
        """Test case for schemas_schema_id_get

        Gets a schema from the ledger  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
