# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.mediation_record import MediationRecord  # noqa: E501
from swagger_client.rest import ApiException


class TestMediationRecord(unittest.TestCase):
    """MediationRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMediationRecord(self):
        """Test MediationRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.mediation_record.MediationRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
