# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.present_proof_api import PresentProofApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPresentProofApi(unittest.TestCase):
    """PresentProofApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.present_proof_api.PresentProofApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_present_proof_create_request_post(self):
        """Test case for present_proof_create_request_post

             Creates a presentation request not bound to any proposal or existing connection       # noqa: E501
        """
        pass

    def test_present_proof_records_get(self):
        """Test case for present_proof_records_get

        Fetch all present-proof exchange records  # noqa: E501
        """
        pass

    def test_present_proof_records_pres_ex_id_credentials_get(self):
        """Test case for present_proof_records_pres_ex_id_credentials_get

        Fetch credentials for a presentation request from wallet  # noqa: E501
        """
        pass

    def test_present_proof_records_pres_ex_id_delete(self):
        """Test case for present_proof_records_pres_ex_id_delete

        Remove an existing presentation exchange record  # noqa: E501
        """
        pass

    def test_present_proof_records_pres_ex_id_get(self):
        """Test case for present_proof_records_pres_ex_id_get

        Fetch a single presentation exchange record  # noqa: E501
        """
        pass

    def test_present_proof_records_pres_ex_id_problem_report_post(self):
        """Test case for present_proof_records_pres_ex_id_problem_report_post

        Send a problem report for presentation exchange  # noqa: E501
        """
        pass

    def test_present_proof_records_pres_ex_id_send_presentation_post(self):
        """Test case for present_proof_records_pres_ex_id_send_presentation_post

        Sends a proof presentation  # noqa: E501
        """
        pass

    def test_present_proof_records_pres_ex_id_send_request_post(self):
        """Test case for present_proof_records_pres_ex_id_send_request_post

        Sends a presentation request in reference to a proposal  # noqa: E501
        """
        pass

    def test_present_proof_records_pres_ex_id_verify_presentation_post(self):
        """Test case for present_proof_records_pres_ex_id_verify_presentation_post

        Verify a received presentation  # noqa: E501
        """
        pass

    def test_present_proof_send_proposal_post(self):
        """Test case for present_proof_send_proposal_post

        Sends a presentation proposal  # noqa: E501
        """
        pass

    def test_present_proof_send_request_post(self):
        """Test case for present_proof_send_request_post

        Sends a free presentation request not bound to any proposal  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
