# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.credentials_api import CredentialsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCredentialsApi(unittest.TestCase):
    """CredentialsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.credentials_api.CredentialsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_credential_credential_id_delete(self):
        """Test case for credential_credential_id_delete

        Remove a credential from the wallet by id  # noqa: E501
        """
        pass

    def test_credential_credential_id_get(self):
        """Test case for credential_credential_id_get

        Fetch a credential from wallet by id  # noqa: E501
        """
        pass

    def test_credential_mime_types_credential_id_get(self):
        """Test case for credential_mime_types_credential_id_get

        Get attribute MIME types from wallet  # noqa: E501
        """
        pass

    def test_credential_revoked_credential_id_get(self):
        """Test case for credential_revoked_credential_id_get

        Query credential revocation status by id  # noqa: E501
        """
        pass

    def test_credentials_get(self):
        """Test case for credentials_get

        Fetch credentials from wallet  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
