# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v10_presentation_send_request_request import V10PresentationSendRequestRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestV10PresentationSendRequestRequest(unittest.TestCase):
    """V10PresentationSendRequestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10PresentationSendRequestRequest(self):
        """Test V10PresentationSendRequestRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v10_presentation_send_request_request.V10PresentationSendRequestRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
