# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.indy_requested_creds_requested_pred import IndyRequestedCredsRequestedPred  # noqa: E501
from swagger_client.rest import ApiException


class TestIndyRequestedCredsRequestedPred(unittest.TestCase):
    """IndyRequestedCredsRequestedPred unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyRequestedCredsRequestedPred(self):
        """Test IndyRequestedCredsRequestedPred"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.indy_requested_creds_requested_pred.IndyRequestedCredsRequestedPred()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
