# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.connection_static_request import ConnectionStaticRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestConnectionStaticRequest(unittest.TestCase):
    """ConnectionStaticRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectionStaticRequest(self):
        """Test ConnectionStaticRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.connection_static_request.ConnectionStaticRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
