# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.introduction_api import IntroductionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIntroductionApi(unittest.TestCase):
    """IntroductionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.introduction_api.IntroductionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_connections_conn_id_start_introduction_post(self):
        """Test case for connections_conn_id_start_introduction_post

        Start an introduction between two connections  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
