# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v10_credential_proposal_request_mand import V10CredentialProposalRequestMand  # noqa: E501
from swagger_client.rest import ApiException


class TestV10CredentialProposalRequestMand(unittest.TestCase):
    """V10CredentialProposalRequestMand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10CredentialProposalRequestMand(self):
        """Test V10CredentialProposalRequestMand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v10_credential_proposal_request_mand.V10CredentialProposalRequestMand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
