# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v20_cred_issue_request import V20CredIssueRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestV20CredIssueRequest(unittest.TestCase):
    """V20CredIssueRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredIssueRequest(self):
        """Test V20CredIssueRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v20_cred_issue_request.V20CredIssueRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
