# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v10_presentation_problem_report_request import V10PresentationProblemReportRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestV10PresentationProblemReportRequest(unittest.TestCase):
    """V10PresentationProblemReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10PresentationProblemReportRequest(self):
        """Test V10PresentationProblemReportRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v10_presentation_problem_report_request.V10PresentationProblemReportRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
