# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.credential_definition_send_request import CredentialDefinitionSendRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestCredentialDefinitionSendRequest(unittest.TestCase):
    """CredentialDefinitionSendRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredentialDefinitionSendRequest(self):
        """Test CredentialDefinitionSendRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.credential_definition_send_request.CredentialDefinitionSendRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
