# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.perform_request import PerformRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestPerformRequest(unittest.TestCase):
    """PerformRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPerformRequest(self):
        """Test PerformRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.perform_request.PerformRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
