# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v10_presentation_create_request_request import V10PresentationCreateRequestRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestV10PresentationCreateRequestRequest(unittest.TestCase):
    """V10PresentationCreateRequestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10PresentationCreateRequestRequest(self):
        """Test V10PresentationCreateRequestRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v10_presentation_create_request_request.V10PresentationCreateRequestRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
