# coding: utf-8

"""
    sp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.menu_form_param import MenuFormParam  # noqa: E501
from swagger_client.rest import ApiException


class TestMenuFormParam(unittest.TestCase):
    """MenuFormParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMenuFormParam(self):
        """Test MenuFormParam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.menu_form_param.MenuFormParam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
