version: "3"
services:
  ngrok-alice:
    image: wernight/ngrok
    command: ngrok http agent-alice:3006 --log stdout
  agent-alice:
    image: acapy-toolbox-ngrok
    build:
      context: ../
      dockerfile: ./demo_dot/Dockerfile.demo
    environment:
      NGROK_NAME: ngrok-alice
    ports:
      - "3007:3007"
    command: aca-py start --arg-file ./configs/alice.yml
